@startuml
abstract class MenuItem {
    -id: Integer
    -name: String
    -price: Double
}

class Drink extends MenuItem {
    -drinkAddons: List<DrinkAddon>
}

class Meal extends MenuItem {
    -cuisine: MealCuisine
}

class Dessert extends MenuItem {
}

class DrinkAddon {
    -id: Integer
    -name: String
    -price: String
}

class MealCuisine {
    -id: Integer;
    -name: String;
}

class Order {
    -id: Integer
    -items: List<MenuItem>
}

Order "1..*" o-- "0..*" MenuItem
Meal "1" *-- "1..*" MealCuisine
Drink "0..*" *-- "1..*" DrinkAddon
@enduml